#! /bin/sh

# Fetch file from store backend
fetch() {
    local TARGET_FILE

    if [ -d "$2" ]; then
        TARGET_FILE="$2/$(basename $1)"
    else
        mkdir -p "$(dirname $2)"
        TARGET_FILE="$2"
    fi

    eval "store_bknd_${STORE_BACKEND} $1" > "${TARGET_FILE}"
}

# [ Store Backends ]
# File store backend
store_bknd_file() {
    cat "${STORE_BASE_PATH}$1"
}

. "$1"
start
